name: CICD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Testing command execution
          id: echo_command
          run: echo "Test Command"